---
- hosts: all
  become_method: sudo
  vars_files:
    - secrets/yourfile.secrets.yml
  vars:
    passwdHPiLo: "{{ vault_HP_ilo_hpadmin_pwd }}"
    passwdORACLEiLo: "{{ vault_ORACLE_ilo_admin_pwd }}"
  roles:
     - {role: iLo , tags: iLo-change }
